In [4]:
import numpy as np

In [1]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [2]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
wist=[1,2,3,4,5]
arr=np.array(wist)

In [10]:
type(wist)

list

In [11]:
arr.shape   #   (rows,columns )

(5,)

In [12]:
type(arr)

numpy.ndarray

In [14]:
my_list1=[1,2,3,4,5]
my_list2=[4,3,5,8,1]
my_list3=[8,1,4,7,9]

arr=np.array([my_list1,my_list2,my_list3])      #we use np.array so we can convert list(array) to numpyn                 array

In [15]:
arr     # it is a three dimensional array

array([[1, 2, 3, 4, 5],
       [4, 3, 5, 8, 1],
       [8, 1, 4, 7, 9]])

In [16]:
arr.shape

(3, 5)

In [18]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 4],
       [3, 5, 8],
       [1, 8, 1],
       [4, 7, 9]])

In [19]:
np.zeros

<function numpy.zeros>

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye(5)            #Eye function (identify matrix) square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# How can we create random distribution of data 
## You give it a shape and it wil populate it with random samples from unifrom distribution over the points 0 to 1 whre 0 is inclusive and 1 is exclusive it can return back 0 but not 1.

In [26]:
np.random.rand(1)

array([0.95751218])

In [28]:
np.random.rand(5)

array([0.8187777 , 0.47850589, 0.82798142, 0.0305711 , 0.6556099 ])

In [29]:
np.random.rand(2,2)

array([[0.82398006, 0.06548155],
       [0.06783519, 0.94106712]])

In [31]:
np.random.rand(3,3)

array([[0.64752655, 0.36580596, 0.40196884],
       [0.98761841, 0.86681488, 0.66616604],
       [0.28342218, 0.41093963, 0.08860817]])

In [32]:
np.random.randint(0,101,5)

array([72, 83, 45, 20, 88])

In [33]:
np.random.randint(0,101,(3,3,))   #give me some random number b/w 0 to 101 in 3*3 matrix form

array([[87, 53, 84],
       [48, 42, 25],
       [63, 52, 33]])

# Indexing (retrieving data/elements from cell)

In [34]:
#Accessing the array element
arr=np.array([1,2,3,4,5,6,7,8,9])   #calculation goes like 0,1,2,3,4,5,6...

In [35]:
arr[3]

4

In [36]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
my_list1=[1,2,3,4,5]
my_list2=[4,3,5,8,1]
my_list3=[8,1,4,7,9]

arr=np.array([my_list1,my_list2,my_list3])     

In [40]:
arr

array([[1, 2, 3, 4, 5],
       [4, 3, 5, 8, 1],
       [8, 1, 4, 7, 9]])

In [41]:
arr[0:2,0:2]

array([[1, 2],
       [4, 3]])

In [44]:
arr[1:,2:4]

array([[5, 8],
       [4, 7]])

In [46]:
arr[1:2,1:4]

array([[3, 5, 8]])

In [47]:
arr=np.arange(0,10)

In [48]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr=np.arange(0,10,step=2)  #It will take a step gap

In [51]:
arr

array([0, 2, 4, 6, 8])

In [52]:
##copy function and broadcasting 
arr

array([0, 2, 4, 6, 8])

In [53]:
arr=np.arange(0,10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr[3:]=100
print(arr)

[  0   1   2 100 100 100 100 100 100 100]


In [60]:
arr1=arr

In [67]:
arr1[3:]=500
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]


array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [71]:
##some conditions are helpful in EDA(exploratory data analysis)

val=2
arr1<=2

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [72]:
arr[arr<300]   ##so there are 3 values in the array which are less than or equal to 300

array([0, 1, 2])

In [73]:
np.ones(4) # Here what happend is all the elements are replaced by 1

array([1., 1., 1., 1.])

In [75]:
np.one((4),dataype=int)

AttributeError: module 'numpy' has no attribute 'one'