In [1]:
import numpy as np

In [2]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [4]:
account_transactions.max()

2000

In [5]:
account_transactions.min()

-400

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
account_transactions+5

array([ 105, -195,  305, -395,  105,  105, -225,  455,  505, 2005])

In [12]:
account_transactions-100

array([   0, -300,  200, -500,    0,    0, -330,  350,  400, 1900])

In [13]:
account_transactions-account_transactions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
account_transactions+account_transactions

array([ 200, -400,  600, -800,  200,  200, -460,  900, 1000, 4000])

In [15]:
account_transactions*account_transactions

array([  10000,   40000,   90000,  160000,   10000,   10000,   52900,
        202500,  250000, 4000000])

In [21]:
np.sqrt(account_transactions)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12164\1560001031.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(account_transactions)


array([10.        ,         nan, 17.32050808,         nan, 10.        ,
       10.        ,         nan, 21.21320344, 22.36067977, 44.72135955])

In [22]:
np.sin(account_transactions)

array([-0.50636564,  0.8732973 , -0.99975584,  0.85091936, -0.50636564,
       -0.50636564,  0.6160642 , -0.68328373, -0.46777181,  0.9300395 ])

In [23]:
np.log(account_transactions)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12164\453755614.py:1: RuntimeWarning: invalid value encountered in log
  np.log(account_transactions)


array([4.60517019,        nan, 5.70378247,        nan, 4.60517019,
       4.60517019,        nan, 6.10924758, 6.2146081 , 7.60090246])

In [28]:
account_transactions.var()    ##variance 

408556.0

In [30]:
account_transactions.std()    ##standard deviation

639.1838546146171

In [31]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
np.arange(0,25).reshape(5,5)   ##creating 2D arrays 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

NameError: name 'arr2d' is not defined